name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate with GCP
        if: ${{ secrets.WIF_PROVIDER != '' && secrets.SA_EMAIL != '' }}
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.SA_EMAIL }}

      - name: Set up Cloud SDK
        if: ${{ secrets.WIF_PROVIDER != '' && secrets.SA_EMAIL != '' }}
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: ">= 363.0.0"

      - name: Sync latest changes to GCP VM and Build
        env:
          REMOTE_USER: shefeeq
          REMOTE_HOST: 35.192.179.177
          REMOTE_PATH: /var/www/dsclinx.ca/
        run: |
          echo "${{ secrets.SSH_KEY }}" > ssh_key
          chmod 600 ./ssh_key
          echo "Cleaning remote directory..."
          ssh -i ./ssh_key -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "sudo su - -c 'cd $REMOTE_PATH && find -not -name \"build.sh\" -delete'" || { echo 'Remote cleanup failed'; exit 1; }
          echo "Syncing files to remote server..."
          sudo rsync -chav -O --no-o --no-g --no-perms --exclude='.git' --exclude='.github' --exclude='gha-creds-*' --exclude='ssh_key' -e 'ssh -i ./ssh_key -o StrictHostKeyChecking=no' $GITHUB_WORKSPACE/ $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH || { echo 'Rsync failed'; exit 1; }
          echo "Running build script on remote server..."
          ssh -i ./ssh_key -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "sudo su - -c 'cd $REMOTE_PATH && ./build.sh'" || { echo 'Remote build script failed'; exit 1; }
